In [8]:
# 課題：NumPyで配列の操作や演算をしよう
# NumPyを利用して、2つの行列の積を計算して結果を表示する
# 計算された行列の要素の最大値を求めて表示する

import numpy as np

# 多次元配列Aを作成
A = np.arange(6).reshape(3, 2)
print(f"Aは{A}です。")

# 多次元配列Bを作成
B = np.arange(8).reshape(2, 4)
print(f"Bは{B}です。")

# AとBの行列の積を計算
Result = np.dot(A, B)
print(f"AとBの行列の積は{Result}です。")

# 計算された行列の要素の最大値を求める
Result2 = np.max(Result)
print(f"計算された行列の要素の最大値は{Result2}です。")


Aは[[0 1]
 [2 3]
 [4 5]]です。
Bは[[0 1 2 3]
 [4 5 6 7]]です。
AとBの行列の積は[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]です。
計算された行列の要素の最大値は47です。
